nginx instances deployment and fix the pipeline issue
dwp/dataworks-aws-bgdc-interface pull request #59
Opened 2021-10-01 09:32 UTC by Alifener

2021-10-01 11:30 UTC, nathanbigaignon approved these changes

2021-10-01 11:35 UTC, rbryett requested changes
No context on this PR. Presuming its going to production.

2021-10-01 11:35 UTC, rbryett commented on security_groups.tf
> +//resource "aws_security_group_rule" "egress_hbase_zookeeper" {
Since this is going to production [?] its worth removing these resources entirely rather than commenting them out else it can cause confusion

2021-10-01 11:35 UTC, rbryett commented on nginx-asg.tf
> +resource "aws_autoscaling_group" "nginx_asg" {
Perhaps puts these into variables rather than hard coding?

2021-10-01 11:35 UTC, rbryett commented on nginx-asg.tf
> +  instance_type   = "t2.medium"
Perhaps puts these into variables rather than hard coding?

2021-10-01 11:35 UTC, rbryett commented on nginx-asg.tf
> +  name                      = "dwx_bgdc_nginx"
This name has underscores where as other resources have names with dashes in. Can we keep this consistent so its easier for when people refer to remote states

2021-10-01 11:35 UTC, rbryett commented on nginx-asg.tf
> +  name               = "dwx-bgdc-nginx-nlb"
This name has dashes where as other resources have names with underscores in. Can we keep this consistent so its easier for when people refer to remote states

2021-10-01 11:35 UTC, rbryett commented on nginx-asg.tf
> +data "aws_network_interface" "lb" {
Something with a more meaningful name that "lb". Again, in case people refer to remote states, this won't be clear.

2021-10-01 11:35 UTC, rbryett commented on nginx-asg.tf
> +
empty lines to remove.

2021-10-01 11:35 UTC, rbryett commented on nginx-asg.tf
> +output "bgdc_dwx_vpc_endpoint_service_name" {
Its best practice to stick outputs into an outputs.tf, that way contributors know where to look for the outputs of this terraform code.

2021-10-01 12:39 UTC, rbryett approved these changes

2021-10-01 12:39 UTC, rbryett approved these changes

2021-10-01 14:40 UTC, nathanbigaignon submitted a review, later dismissed

2021-10-05 10:11 UTC, nathanbigaignon approved these changes
LGTM

2021-10-05 10:15 UTC, merged